AWSTemplateFormatVersion: 2010-09-09
Description: Creates the SES pipeline's resources for apsov.

Resources:
  ReceiptRuleSet:
    # There can only be one active ruleset in a given AWS account & region.
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !Sub ${AWS::StackName}-receipt-rule-set

  DropNoReplyReceiptRule:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: !Sub ${AWS::StackName}-receipt-rule-set
      Rule:
        Name: drop-noreply-receiptrule
        Recipients:
          - noreply@mail-ap2.nicecxone-sov1.ap
          - bounce@mail-ap2.nicecxone-sov1.ap
        Enabled: true
        ScanEnabled: true
        TlsPolicy: Optional
        Actions:
          - StopAction:
              Scope: RuleSet
    DependsOn:
      - ReceiptRuleSet

  UksovMicroservicesSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: channels-email-ses-sns-topic-apsov
      TopicName: channels-email-ses-sns-topic-apsov

  UksovMicroservicesReceiptRule:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: !Sub ${AWS::StackName}-receipt-rule-set
      After: !Ref DropNoReplyReceiptRule
      Rule:
        Name: apsov-receipt-rule
        Recipients:
          - mail-ap2.nicecxone-sov1.ap
          - mailtest-ap2.nicecxone-sov1.ap
        Enabled: true
        ScanEnabled: true
        TlsPolicy: Optional
        Actions:
          - S3Action:
              BucketName: aplo-email-ses-storage
              TopicArn: !Sub arn:aws:sns:new-region-6:${AWS::AccountId}:channels-email-ses-sns-topic-apsov
    DependsOn:
      - ReceiptRuleSet
